- name: Worker
  gather_facts: false
  hosts: all
  become: true
  tasks:
    - name: Upload token
      ansible.builtin.copy:
        src: {{ config_dir }}/token
        dest: /tmp/token
    - name: Check if k0s is running
      ansible.builtin.shell:
        cmd: |
          pgrep k0s
      register: k0s_running
      ignore_errors: true
    - name: Install and start k0s worker
      when: k0s_running.rc != 0
      ansible.builtin.shell:
        cmd: |
          k0s install worker --enable-cloud-provider --token-file /tmp/token
          k0s start