- name: Start master
  gather_facts: false
  hosts: master
  become: true
  strategy: free
  tasks:
    - name: Start k0s master
      ansible.builtin.shell:
        cmd: |
          snap install yq
          
          mkdir -p /etc/k0s
          k0s config create > /etc/k0s/k0s.yaml
          export IP=$(curl -s ipv4.icanhazip.com)
          yq eval -i ".spec.api.sans += \"$IP\"" /etc/k0s/k0s.yaml
          
          k0s install controller -c /etc/k0s/k0s.yaml
          k0s start
          k0s token create --role=worker --expiry=1h > /tmp/token
    - name: Download node token
      ansible.builtin.fetch:
        src: /tmp/token
        dest: token
        flat: yes