alsologtostderr = false
ami = 'ami-09ca9cb836d95b14c'
config = 'config.toml'
instance = 't3a.micro'
key = '/path/to/your/id_rsa.pub'
log_backtrace_at = ''
log_dir = ''
log_link = ''
logbuflevel = 0
logtostderr = false
name = 'infralink'
repository = '868331154982.dkr.ecr.us-east-2.amazonaws.com/infralink'
stderrthreshold = '2'
user = 'ubuntu'
v = '0'
verbose = true
vmodule = ''
