[package]
name = "pricing-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.20"
serde = { version = "1.0.188", features = ["derive"] }
miette = "5.10.0"
serde_json = "1.0.107"
